# Generated by Django 4.2.1 on 2023-10-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account', models.IntegerField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(max_length=400, null=True)),
                ('password', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
