# Generated by Django 4.2.1 on 2023-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byte_locker_app', '0002_alter_accounts_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
